<?php

/**
 * @file
 * Contains create_menu_permissions.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Session\AccountInterface;
use Drupal\Component\Utility\Html;


/**
 * Implements hook_menu_create_access().
 *
 * Checks if the current user has the permission to create a new menu.
 */
function create_menus_permission_menu_create_access(AccountInterface $account, array $context, $entity_bundle) {
	if ($account->hasPermission('create new menu')) {
		return AccessResult::allowed();
	}

	return AccessResult::forbidden();
}